### ISSUE TITLE
Error: /Lego/Technic/Door/Parts - Folder not found

### ISSUE THREAD

**Issue by sourcelocation** [thegamingcomputerbomb/lego-iris#1]
please help, it seems I don't have this folder. Please help

**Comment by thegamingcomputerbomb** [comment]
@ExeRhythm Can you please provide the full message that the error gave you (if the title isn't the full message).
also try placing some technic parts in a new project before opening the file.

**Comment by ExeRhythm** [comment]
Thank you, I got it working.

**Comment by sourcelocation** [comment]
Finally parts have been downloaded. Took AGES! :))
